spring:
  datasource:
    url: jdbc:mysql://localhost:3307/order_system?useSSL=false&allowPublicKeyRetrieval=true
    username: appuser
    password: apppassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
